### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by haxerzin** [acuifex/proxychains#1]
I'm not sure how to use it.. For example, original proxychains can be used directly from the terminal using: `proxychains curl https://something.com/` or `proxychains firefox`.

**Comment by acuifex** [comment]
hello! i might have chose a confusing name.
this is intended to be used as a library, to make other projects use proxy chains (i.e. requests, httpx, other libraries that do requests) or create bare proxied sockets. so it's useless by itself.
it's not too different from libraries listed in the readme, i've just cleaned up the code, and made https chains work.
